steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'generator/Dockerfile.streamlit', '-t', 'gcr.io/$PROJECT_ID/generator-frontend:latest', '.']
images: ['gcr.io/$PROJECT_ID/generator-frontend:latest'] 