steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'interview/Dockerfile.streamlit', '-t', 'gcr.io/$PROJECT_ID/interview-frontend:latest', '.']
images: ['gcr.io/$PROJECT_ID/interview-frontend:latest'] 