[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f8ff"
textColor = "#262730"

[server]
headless = true
port = 8502
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 